<a href="https://colab.research.google.com/github/piusAI/Pytorch_Study/blob/main/tensor_tutorial_01_Tensor.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
%matplotlib inline

|| **Tensors** ||


Tensors
==========================

Tensors are a specialized data structure that are very similar to arrays and matrices.
In PyTorch, we use tensors to encode the inputs and outputs of a model, as well as the model’s parameters.

Tensors are similar to `NumPy’s <https://numpy.org/>`_ ndarrays, except that tensors can run on GPUs or other hardware accelerators. In fact, tensors and
NumPy arrays can often share the same underlying memory, eliminating the need to copy data (see `bridge-to-np-label`). Tensors
are also optimized for automatic differentiation (we'll see more about that later in the `Autograd <autograd_tutorial.html>`__
section). If you’re familiar with ndarrays, you’ll be right at home with the Tensor API. If not, follow along!



In [ ]:
import torch
import numpy as np

Initializing a Tensor
~~~~~~~~~~~~~~~~~~~~~
Tensors can be initialized in various ways. Take a look at the following examples:

**Directly from data**

Tensors can be created directly from data. The data type is automatically inferred.



In [ ]:
data = [[1,2], [6,12]]
x_data = torch.tensor(data)


tensor([[ 1,  2],
        [ 6, 12]])


**From a NumPy array**

Tensors can be created from NumPy arrays (and vice versa - see `bridge-to-np-label`).



In [ ]:
np_array = np.array(data)
x_np= torch.from_numpy(np_array)
print(x_np)

tensor([[ 1,  2],
        [ 6, 12]])


**From another tensor:**

The new tensor retains the properties (shape, datatype) of the argument tensor, unless explicitly overridden.



In [ ]:
x_t = torch.rand_like(x_data,dtype=torch.float)
print(x_t)

tensor([[0.3458, 0.4284],
        [0.4279, 0.7951]])


In [ ]:
x_ones = torch.ones_like(x_data)

print(f"Ones Tensor : \n {x_ones}\n")

x_rand = torch.rand_like(x_data, dtype = torch.float)
print(f'rand tensor : \n{x_rand}')

Ones Tensor : 
 tensor([[1, 1],
        [1, 1]])

rand tensor : 
tensor([[0.1714, 0.8850],
        [0.8292, 0.0928]])


In [ ]:
x_ones = torch.ones_like(x_data) # retains the properties of x_data
print(f"Ones Tensor: \n {x_ones} \n")

x_rand = torch.rand_like(x_data, dtype=torch.float) # overrides the datatype of x_data
print(f"Random Tensor: \n {x_rand} \n")

Ones Tensor: 
 tensor([[1, 1],
        [1, 1]]) 

Random Tensor: 
 tensor([[0.2395, 0.7912],
        [0.9624, 0.5567]]) 



**With random or constant values:**

``shape`` is a tuple of tensor dimensions. In the functions below, it determines the dimensionality of the output tensor.



In [ ]:
shape= (2,3,) #Same as shape =[2,3]
rand_tensor = torch.rand(shape)
one_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f'rand_tensor : \n {rand_tensor}\n')
print(f'one_tensor : \n {one_tensor}\n')
print(f'zeros_tensor : \n {zeros_tensor}')

rand_tensor : 
 tensor([[0.5846, 0.3132, 0.8577],
        [0.2184, 0.5686, 0.8161]])

one_tensor : 
 tensor([[1., 1., 1.],
        [1., 1., 1.]])

zeros_tensor : 
 tensor([[0., 0., 0.],
        [0., 0., 0.]])


--------------




Attributes of a Tensor
~~~~~~~~~~~~~~~~~
Tensor attributes describe their shape, datatype, and the device on which they are stored.



In [ ]:
tensor = torch.rand(3,4)

print(f"shape of tensor : {tensor.shape}")
print(f"Datatype of tensor : {tensor.dtype}")
print(f"Device tensor is stored on {tensor.device}")

shape of tensor : torch.Size([3, 4])
Datatype of tensor : torch.float32
Device tensor is stored on cpu


In [ ]:
tensor = torch.rand(3,4)

print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

--------------




Operations on Tensors
~~~~~~~~~~~~~~~~~
Over 1200 tensor operations, including arithmetic, linear algebra, matrix manipulation (transposing,
indexing, slicing), sampling and more are
comprehensively described `here <https://pytorch.org/docs/stable/torch.html>`__.

Each of these operations can be run on the GPU (at typically higher speeds than on a
CPU). If you’re using Colab, allocate a GPU by going to Runtime > Change runtime type > GPU.

By default, tensors are created on the CPU. We need to explicitly move tensors to the GPU using
``.to`` method (after checking for GPU availability). Keep in mind that copying large tensors
across devices can be expensive in terms of time and memory!



In [ ]:
# We move our tensor to the GPU if available
if torch.cuda.is_available():
  tensor = tensor.to('cuda')

Try out some of the operations from the list.
If you're familiar with the NumPy API, you'll find the Tensor API a breeze to use.




**Standard numpy-like indexing and slicing:**



In [ ]:
tt = np.random.randn(4,4)
tt2 = np.round(tt, 2)
tot = torch.from_numpy(tt2)
print(tot,"\n")

tensor = torch.rand(4,4,dtype=float)

tensor_one = torch.ones(4,4,dtype=float)
print(f'tensor_one: \n {tensor_one}\n')


print(f'First row : {tensor[0]}')
print(f'First Columns :{tensor[:,0]}')
print(f'Last columns : {tensor[...,-1]}')
tensor[:,1]=0
print(tensor,'\n')

print(f'it is test : {tot[:,2]}')
# print(f'Last columns : {tensor[:,-1]}')

tensor([[-0.9600,  1.2200, -0.1400, -1.6100],
        [ 0.9200,  0.3100,  0.1900, -0.4100],
        [ 0.4900, -0.7400, -1.0400, -0.4100],
        [-1.0800, -0.2000, -0.0200, -0.1400]], dtype=torch.float64) 

tensor_one: 
 tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]], dtype=torch.float64)

First row : tensor([0.7721, 0.3717, 0.8392, 0.2734], dtype=torch.float64)
First Columns :tensor([0.7721, 0.3509, 0.6450, 0.9282], dtype=torch.float64)
Last columns : tensor([0.2734, 0.5079, 0.0491, 0.1870], dtype=torch.float64)
tensor([[0.7721, 0.0000, 0.8392, 0.2734],
        [0.3509, 0.0000, 0.8415, 0.5079],
        [0.6450, 0.0000, 0.7396, 0.0491],
        [0.9282, 0.0000, 0.4876, 0.1870]], dtype=torch.float64) 

it is test : tensor([-0.1400,  0.1900, -1.0400, -0.0200], dtype=torch.float64)


**Joining tensors** You can use ``torch.cat`` to concatenate a sequence of tensors along a given dimension.
See also `torch.stack <https://pytorch.org/docs/stable/generated/torch.stack.html>`__,
another tensor joining op that is subtly different from ``torch.cat``.



In [ ]:
tt1= torch.cat([tensor, tot,tensor, tensor_one],axis=0)
print(f'tt1: \n {tt1}')
tt2= torch.cat([tensor,tot, tensor, tensor_one],dim=1)
print(f'tt2 : \n {tt2}')

tt1: 
 tensor([[ 0.7721,  0.0000,  0.8392,  0.2734],
        [ 0.3509,  0.0000,  0.8415,  0.5079],
        [ 0.6450,  0.0000,  0.7396,  0.0491],
        [ 0.9282,  0.0000,  0.4876,  0.1870],
        [-0.9600,  1.2200, -0.1400, -1.6100],
        [ 0.9200,  0.3100,  0.1900, -0.4100],
        [ 0.4900, -0.7400, -1.0400, -0.4100],
        [-1.0800, -0.2000, -0.0200, -0.1400],
        [ 0.7721,  0.0000,  0.8392,  0.2734],
        [ 0.3509,  0.0000,  0.8415,  0.5079],
        [ 0.6450,  0.0000,  0.7396,  0.0491],
        [ 0.9282,  0.0000,  0.4876,  0.1870],
        [ 1.0000,  1.0000,  1.0000,  1.0000],
        [ 1.0000,  1.0000,  1.0000,  1.0000],
        [ 1.0000,  1.0000,  1.0000,  1.0000],
        [ 1.0000,  1.0000,  1.0000,  1.0000]], dtype=torch.float64)
tt2 : 
 tensor([[ 0.7721,  0.0000,  0.8392,  0.2734, -0.9600,  1.2200, -0.1400, -1.6100,
          0.7721,  0.0000,  0.8392,  0.2734,  1.0000,  1.0000,  1.0000,  1.0000],
        [ 0.3509,  0.0000,  0.8415,  0.5079,  0.9200,  0.3100,  

In [ ]:
t1 = torch.cat([tensor, tensor, tensor], dim=1)
print(t1)

**Arithmetic operations**



In [ ]:
y1 = tot @ tensor.T
y2 = tot.matmul(tensor.T)
# print(y2==y1)

y3= torch.ones_like(y2)
y5 = torch.rand_like(y3)
y4= torch.matmul(tot, tensor.T, out=y5)

print(y1 == y2)
# print(y2 == y4)
print(y1)
print(y5)



z1 = tot * tot
z2 = tot.mul(tot)

z3= torch.rand_like(tot)
torch.mul(tot,tot, out=z3)

print(z1)
print(z3)

tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])
tensor([[-1.2988, -1.2724, -0.8019, -1.2604],
        [ 0.7577,  0.2744,  0.7138,  0.8699],
        [-0.6065, -0.9115, -0.4733, -0.1290],
        [-0.8890, -0.4669, -0.7183, -1.0384]], dtype=torch.float64)
tensor([[-1.2988, -1.2724, -0.8019, -1.2604],
        [ 0.7577,  0.2744,  0.7138,  0.8699],
        [-0.6065, -0.9115, -0.4733, -0.1290],
        [-0.8890, -0.4669, -0.7183, -1.0384]], dtype=torch.float64)
tensor([[9.2160e-01, 1.4884e+00, 1.9600e-02, 2.5921e+00],
        [8.4640e-01, 9.6100e-02, 3.6100e-02, 1.6810e-01],
        [2.4010e-01, 5.4760e-01, 1.0816e+00, 1.6810e-01],
        [1.1664e+00, 4.0000e-02, 4.0000e-04, 1.9600e-02]], dtype=torch.float64)
tensor([[9.2160e-01, 1.4884e+00, 1.9600e-02, 2.5921e+00],
        [8.4640e-01, 9.6100e-02, 3.6100e-02, 1.6810e-01],
        [2.4010e-01, 5.4760e-01, 1.0816e+00, 1.6810e-01],
        [1.1664e+00, 4.

In [ ]:
# This computes the matrix multiplication between two tensors. y1, y2, y3 will have the same value
y1 = tensor @ tensor.T
y2 = tensor.matmul(tensor.T)

y3 = torch.rand_like(tensor)
torch.matmul(tensor, tensor.T, out=y3)


# This computes the element-wise product. z1, z2, z3 will have the same value
z1 = tensor * tensor
z2 = tensor.mul(tensor)

z3 = torch.rand_like(tensor)
torch.mul(tensor, tensor, out=z3)

**Single-element tensors** If you have a one-element tensor, for example by aggregating all
values of a tensor into one value, you can convert it to a Python
numerical value using ``item()``:



In [ ]:
agg=tot.sum()
agg_item=agg.item()
print(agg_item, type(agg_item))
print(agg)

-3.62 <class 'float'>
tensor(-3.6200, dtype=torch.float64)


In [ ]:
agg = tensor.sum()
agg_item = agg.item()
print(agg_item, type(agg_item))

**In-place operations**
Operations that store the result into the operand are called in-place. They are denoted by a ``_`` suffix.
For example: ``x.copy_(y)``, ``x.t_()``, will change ``x``.



In [ ]:
print(tot,"\n")
tot.add_(5)
print(tot)

tensor([[-0.9600,  1.2200, -0.1400, -1.6100],
        [ 0.9200,  0.3100,  0.1900, -0.4100],
        [ 0.4900, -0.7400, -1.0400, -0.4100],
        [-1.0800, -0.2000, -0.0200, -0.1400]], dtype=torch.float64) 

tensor([[4.0400, 6.2200, 4.8600, 3.3900],
        [5.9200, 5.3100, 5.1900, 4.5900],
        [5.4900, 4.2600, 3.9600, 4.5900],
        [3.9200, 4.8000, 4.9800, 4.8600]], dtype=torch.float64)


In [ ]:
print(tensor, "\n")
tensor.add_(5)
print(tensor)

<div class="alert alert-info"><h4>Note</h4><p>In-place operations save some memory, but can be problematic when computing derivatives because of an immediate loss
     of history. Hence, their use is discouraged.</p></div>



--------------





Bridge with NumPy
~~~~~~~~~~~~~~~~~
Tensors on the CPU and NumPy arrays can share their underlying memory
locations, and changing one will change	the other.



Tensor to NumPy array




In [ ]:
t=torch.ones(7)
print(f"t: {t}")

n=t.numpy()
print(f"n:{n}")

t: tensor([1., 1., 1., 1., 1., 1., 1.])
n:[1. 1. 1. 1. 1. 1. 1.]


In [ ]:
t.add_(4)

print(t)
print(n)

tensor([9., 9., 9., 9., 9., 9., 9.])
[9. 9. 9. 9. 9. 9. 9.]


In [ ]:
t = torch.ones(5)
print(f"t: {t}")
n = t.numpy()
print(f"n: {n}")

A change in the tensor reflects in the NumPy array.



In [ ]:
t.add_(1)
print(f"t: {t}")
print(f"n: {n}")

NumPy array to Tensor
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^



In [ ]:
yoyo=np.ones(5)
whywhy=torch.from_numpy(yoyo)

In [ ]:
np.add(yoyo,5,out = yoyo)
print(f'yoyo:{yoyo}')
print(f'whywhy:{whywhy}')

yoyo:[11. 11. 11. 11. 11.]
whywhy:tensor([11., 11., 11., 11., 11.], dtype=torch.float64)


In [ ]:
n = np.ones(5)
t = torch.from_numpy(n)

Changes in the NumPy array reflects in the tensor.



In [ ]:
np.add(n, 1, out=n)
print(f"t: {t}")
print(f"n: {n}")